# Generated by Django 6.0 on 2026-02-02 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_interne', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SORTI', 'Sorti'), ('DECEDE', 'Décédé'), ('ARCHIVE', 'Archivé')], default='ACTIF', max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('PACSE', 'Pacsé(e)'), ('CONCUBINAGE', 'En concubinage'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve'), ('SEPARE', 'Séparé(e)')], max_length=50, null=True, verbose_name='Situation familiale')),
                ('civilite', models.CharField(choices=[('M.', 'M.'), ('MME', 'Mme')], max_length=5)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('nom_naissance', models.CharField(blank=True, max_length=30)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=50)),
                ('situation', models.CharField(blank=True, choices=[('SCOLARISE', 'Scolarisé'), ('ETUDIANT', 'Étudiant'), ('ACTIF', 'En activité'), ('CHOMAGE', 'Sans emploi / chômage'), ('RSA', 'Bénéficiaire RSA'), ('HANDICAP', 'Situation de handicap'), ('SANS_ACTIVITE', 'Sans activité')], max_length=25, verbose_name='Situation actuelle')),
                ('nir', models.CharField(blank=True, max_length=15)),
                ('numero_caf', models.CharField(blank=True, max_length=10)),
                ('numero_france_travail', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_fiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=100)),
                ('telephone_mobile', models.CharField(blank=True, max_length=20)),
                ('telephone_fixe', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('motif_sortie', models.CharField(blank=True, choices=[('SEPARATION', 'Séparation'), ('DIVORCE', 'Divorce'), ('DECES', 'Décès'), ('DEMENAGEMENT', 'Déménagement'), ('PLACEMENT', 'Placement'), ('MAJORITE', 'Majorité'), ('FIN_DROITS', 'Fin de droits'), ('AUTRE', 'Autre')], max_length=50, null=True)),
                ('detail_sortie', models.TextField(blank=True, null=True)),
                ('est_decede', models.BooleanField(default=False)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBeneficiaireLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('IDENTITE', "Pièce d'identité"), ('DOMICILIATION', 'Justificatif de domicile'), ('RESSOURCES', 'Justificatif de ressources'), ('AUTRE', 'Autre document')], max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LienFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('PARENT', 'Parent (Père/Mère)'), ('ENFANT', 'Enfant'), ('CONJOINT', 'Conjoint / Concubin'), ('PLACEMENT', "Famille d'accueil / Placement"), ('TUTEUR', 'Tuteur / Curateur'), ('TIERS', 'Tiers de confiance'), ('AUTRE', 'Autre lien')], max_length=20)),
                ('vit_au_foyer', models.BooleanField(default=True, help_text="L'individu réside-t-il physiquement avec cette personne ?")),
                ('est_responsable_legal', models.BooleanField(default=False)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Lien familial',
                'verbose_name_plural': 'Liens familiaux',
            },
        ),
    ]
