# Generated by Django 6.0 on 2026-02-02 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaire', '0001_initial'),
        ('ged', '0001_initial'),
        ('mds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaire',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='mds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='mds.mds'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='referent_mds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires_suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentbeneficiairelink',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaire.beneficiaire'),
        ),
        migrations.AddField(
            model_name='documentbeneficiairelink',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentbeneficiairelink',
            name='document_ged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ged.documentged'),
        ),
        migrations.AddField(
            model_name='lienfamilial',
            name='personne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liens_inities', to='beneficiaire.beneficiaire'),
        ),
        migrations.AddField(
            model_name='lienfamilial',
            name='personne_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liens_recus', to='beneficiaire.beneficiaire'),
        ),
        migrations.AddIndex(
            model_name='beneficiaire',
            index=models.Index(fields=['nom', 'prenom'], name='beneficiair_nom_c6542a_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaire',
            index=models.Index(fields=['code_interne'], name='beneficiair_code_in_ba36dc_idx'),
        ),
        migrations.AddIndex(
            model_name='lienfamilial',
            index=models.Index(fields=['personne_a', 'personne_b'], name='beneficiair_personn_b6350a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lienfamilial',
            unique_together={('personne_a', 'personne_b', 'type_lien')},
        ),
    ]
