# 📁 Emplacement : beneficiaire/migrations/0004_transfertmds.py
# Generated by Django 6.0 on 2026-10-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaire', '0003_add_numero_genesis'),
        ('mds', '0004_demijourneereception_lieu_externe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertMDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='beneficiaire.beneficiaire')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_demandes', to=settings.AUTH_USER_MODEL)),
                ('mds_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_entrants', to='mds.mds')),
                ('mds_origine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_sortants', to='mds.mds')),
                ('referent_sortant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_sortis', to=settings.AUTH_USER_MODEL)),
                ('transfere_avec', models.ForeignKey(blank=True, help_text='Usager principal si transféré avec son foyer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='beneficiaire.beneficiaire')),
            ],
            options={
                'verbose_name': 'Transfert de MDS',
                'verbose_name_plural': 'Transferts de MDS',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
