# Generated by Django 6.0 on 2026-02-02 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAFASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('ressources', models.JSONField(default=dict)),
                ('charges', models.JSONField(default=dict)),
                ('nb_personnes_foyer', models.PositiveSmallIntegerField(editable=False)),
                ('reste_a_vivre', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CAPCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_emission', models.DateField()),
                ('date_envoi', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionAFASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type_decision', models.CharField(choices=[('ACCORD', 'Accord'), ('REFUS', 'Refus')], max_length=10)),
                ('code_decision', models.CharField(max_length=2)),
                ('montant_accorde', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duree_accordee', models.PositiveSmallIntegerField()),
                ('motivation', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DemandeAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aide_code', models.CharField(blank=True, max_length=50)),
                ('montant_sollicite', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('BROUILLON', 'Draft'), ('DEPOSEE', 'Submitted'), ('EN_INSTRUCTION', 'In progress'), ('VALIDE', 'Validated'), ('ACCORDEE', 'Granted'), ('AJO', 'Postponed'), ('ANNULEE', 'Cancelled')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evaluation_sociale', models.TextField(blank=True)),
                ('numero_dossier', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSocialeAFASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code_instruction', models.CharField(blank=True, choices=[('1', 'Droits en attente'), ('2', 'Droits suspendus'), ('3', 'Droits diminués'), ('4', 'Difficulté budgétaire ponctuelle / crise familiale'), ('5', 'Surendettement'), ('6', 'Catastrophes naturelles / crise externe à la famille'), ('7', 'Aucun droit en attente et sans revenus connus')], max_length=2)),
                ('situation_sociale', models.TextField()),
                ('analyse_problematique', models.TextField()),
                ('justification_demande', models.TextField()),
                ('commentaire_familial', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MotifDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('IDENTITE', 'ID document'), ('LIVRET_FAMILLE', 'Family record book'), ('RIB', 'Bank account details'), ('DOMICILE', 'Proof of address'), ('RESSOURCES', 'Income proof'), ('CHARGES', 'Expense proof'), ('AUTRE', 'Other document')], max_length=50)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'Pending'), ('VALIDE', 'OK')], default='EN_ATTENTE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RegieUrgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_urgence', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('motif_urgence', models.TextField()),
                ('date_rendez_vous_regie', models.DateTimeField(blank=True, null=True)),
                ('regisseur', models.CharField(blank=True, max_length=200)),
                ('date_versement', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(max_length=50)),
                ('statut_nouveau', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
