# Generated by Django 6.0 on 2026-02-02 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AidFi', '0001_initial'),
        ('beneficiaire', '0001_initial'),
        ('ged', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetafase',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='budgetafase',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='capcheque',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caps_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionafase',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='decisionafase',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.CreateModel(
            name='DemandeAFASE',
            fields=[
                ('demandeaide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AidFi.demandeaide')),
                ('numero_genesis', models.CharField(blank=True, max_length=50)),
                ('premiere_demande', models.BooleanField(default=True)),
                ('duree_demande', models.PositiveSmallIntegerField(default=1)),
                ('avis_ts', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], max_length=15)),
            ],
            options={
                'verbose_name': 'Demande AFASE',
                'verbose_name_plural': 'Demandes AFASE',
                'db_table': 'AidFi_demandeafase',
            },
            bases=('AidFi.demandeaide',),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='beneficiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_aide', to='beneficiaire.beneficiaire'),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='demandeur',
            field=models.ForeignKey(help_text='Personne ayant formulé la demande (parent, jeune majeur, tuteur, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='demandes_formulees', to='beneficiaire.beneficiaire'),
        ),
        migrations.AddField(
            model_name='capcheque',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cap_cheque', to='AidFi.demandeaide'),
        ),
        migrations.AddField(
            model_name='evaluationsocialeafase',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='evaluationsocialeafase',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='motif_demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='AidFi.motifdemande'),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='AidFi.demandeaide'),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='document_ged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ged.documentged'),
        ),
        migrations.AddField(
            model_name='regieurgence',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regies_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regieurgence',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regie_urgence', to='AidFi.demandeaide'),
        ),
        migrations.AddField(
            model_name='suividemande',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suividemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='AidFi.demandeaide'),
        ),
        migrations.AddField(
            model_name='typeaide',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motifdemande',
            name='type_aide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motifs_demande', to='AidFi.typeaide'),
        ),
        migrations.AddField(
            model_name='demandeaide',
            name='type_aide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='AidFi.typeaide'),
        ),
        migrations.AddField(
            model_name='evaluationsocialeafase',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_afase', to='AidFi.demandeafase'),
        ),
        migrations.AddField(
            model_name='decisionafase',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='AidFi.demandeafase'),
        ),
        migrations.AddField(
            model_name='budgetafase',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='AidFi.demandeafase'),
        ),
    ]
