# Generated by Django 6.0 on 2026-05-25 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AidFi", "0005_documentafase"),
        ("ged", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetafase",
            options={
                "verbose_name": "Budget AFASE",
                "verbose_name_plural": "Budgets AFASE",
            },
        ),
        migrations.AlterModelOptions(
            name="decisionafase",
            options={
                "verbose_name": "Décision AFASE",
                "verbose_name_plural": "Décisions AFASE",
            },
        ),
        migrations.AlterModelOptions(
            name="documentafase",
            options={
                "verbose_name": "Document AFASE",
                "verbose_name_plural": "Documents AFASE",
            },
        ),
        migrations.AlterModelOptions(
            name="evaluationsocialeafase",
            options={
                "verbose_name": "Évaluation sociale AFASE",
                "verbose_name_plural": "Évaluations sociales AFASE",
            },
        ),
        migrations.RemoveField(
            model_name="documentafase",
            name="date_ajout",
        ),
        migrations.AddField(
            model_name="piecejustificative",
            name="date_verification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="piecejustificative",
            name="obligatoire",
            field=models.BooleanField(
                default=False, help_text="Document requis pour la validation"
            ),
        ),
        migrations.AddField(
            model_name="piecejustificative",
            name="verifie_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Cadre ayant validé ce document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pieces_verifiees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="budgetafase",
            name="nb_personnes_foyer",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="budgetafase",
            name="reste_a_vivre",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="decisionafase",
            name="code_decision",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="decisionafase",
            name="decide_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisions_afase",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="decisionafase",
            name="duree_accordee",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="decisionafase",
            name="montant_accorde",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="decisionafase",
            name="type_decision",
            field=models.CharField(
                choices=[
                    ("ACCORD", "Accord"),
                    ("REFUS", "Refus"),
                    ("AJO", "Ajournement"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="documentafase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="documentafase",
            name="demande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="AidFi.demandeafase",
            ),
        ),
        migrations.AlterField(
            model_name="documentafase",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ged.documentged"
            ),
        ),
        migrations.AlterField(
            model_name="documentafase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AlterField(
            model_name="evaluationsocialeafase",
            name="analyse_problematique",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="evaluationsocialeafase",
            name="code_instruction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Droits en attente"),
                    ("2", "Droits suspendus"),
                    ("3", "Droits diminués"),
                    ("4", "Difficulté budgétaire ponctuelle / crise familiale"),
                    ("5", "Surendettement"),
                    ("6", "Catastrophes naturelles / crise externe à la famille"),
                    ("7", "Aucun droit en attente et sans revenus connus"),
                ],
                max_length=2,
                verbose_name="Code de demande AFASE",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationsocialeafase",
            name="situation_sociale",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="statut",
            field=models.CharField(
                choices=[("EN_ATTENTE", "En attente"), ("VALIDE", "Validé")],
                default="EN_ATTENTE",
                max_length=15,
            ),
        ),
    ]
