# Generated by Django 6.0 on 2026-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidFi', '0006_alter_budgetafase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeaide',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Draft'), ('DEPOSEE', 'Submitted'), ('EN_INSTRUCTION', 'In progress'), ('VALIDE', 'Validated'), ('ACCORDEE', 'Granted'), ('REFUSEE', 'Refused'), ('AJO', 'Postponed'), ('ANNULEE', 'Cancelled')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='piecejustificative',
            name='type_piece',
            field=models.CharField(choices=[('IDENTITE', 'ID document'), ('LIVRET_FAMILLE', 'Family record book'), ('RIB', 'Bank account details'), ('DOMICILE', 'Proof of address'), ('RESSOURCES', 'Income proof'), ('CHARGES', 'Expense proof'), ('AUTRE', 'Other document'), ('DECISION', 'Decision')], max_length=50),
        ),
    ]
