# Generated by Django 6.0 on 2026-02-02 23:41

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creation'), ('READ', 'Consultation'), ('UPDATE', 'Update'), ('DELETE', 'Deletion'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Data export'), ('PRINT', 'Print'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejection'), ('SEND', 'Send'), ('RECEIVE', 'Receive')], max_length=20)),
                ('niveau', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict, help_text='Before/after data, metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('methode_http', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duree_execution', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Capacite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code technique stable (snake_case)', max_length=100, unique=True)),
                ('nom', models.CharField(help_text='Nom lisible (interface / admin)', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Capacité',
                'verbose_name_plural': 'Capacités',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(help_text='Unique parameter identifier', max_length=100, unique=True)),
                ('valeur', models.TextField(help_text='Parameter value (stored as text)')),
                ('type_valeur', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DATE', 'Date'), ('DATETIME', 'Datetime')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(help_text='Logical grouping (SYSTEM, SECURITY, BUSINESS, etc.)', max_length=100)),
                ('modifiable', models.BooleanField(default=True, help_text='Can be modified via the interface')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categorie', 'cle'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(help_text='Code du profil (ex: MDS_Cadres, DITAS_Direction)', max_length=100, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_service', models.CharField(choices=[('CENTRAL', 'Central service'), ('SUPPORT', 'Support service'), ('TERRITOIRE', 'Territorial service')], default='CENTRAL', max_length=20)),
                ('direction', models.CharField(choices=[('DITAS', 'DITAS - Direction of Territories and Social Action'), ('DEF', 'DEF - Child-Family Direction')], max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=100)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('responsable_designation', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('telephone_professionnel', models.CharField(blank=True, default='', max_length=20)),
                ('telephone_mobile', models.CharField(blank=True, default='', max_length=20)),
                ('email_professionnel', models.EmailField(blank=True, default='', max_length=254)),
                ('est_remplacant', models.BooleanField(default=False)),
                ('numero_interne', models.CharField(blank=True, default='', max_length=20)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('date_dernier_changement_mdp', models.DateField(blank=True, null=True)),
                ('date_expiration_mdp', models.DateField(blank=True, null=True)),
                ('ldap_dn', models.CharField(blank=True, default='', max_length=255)),
                ('force_change_password', models.BooleanField(default=False)),
                ('double_authentification_active', models.BooleanField(default=False)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('signature_manuscrite', models.CharField(blank=True, default='', max_length=100)),
                ('derniere_connexion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('nombre_connexions', models.PositiveIntegerField(default=0)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_crees', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
