# Generated by Django 6.0 on 2026-02-02 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('mds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mds_principale_HIDDEN',
        ),
        migrations.AddField(
            model_name='user',
            name='mds_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs_principaux', to='mds.mds'),
        ),
    ]
