# Generated by Django 6.0 on 2026-05-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_user_mds_principale_hidden_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="matricule",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
