# Generated by Django 6.0 on 2026-02-02 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaire', '0001_initial'),
        ('contenttypes', '0001_initial'),
        ('ged', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('priorite', models.CharField(choices=[('normale', 'Normale'), ('importante', 'Importante'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('motif', models.CharField(choices=[('suivi_dossier', 'Suivi de dossier'), ('piece_manquante', 'Pièce manquante'), ('validation_document', 'Validation de document'), ('mise_a_jour_situation', 'Mise à jour situation'), ('demande_rdv', 'Demande de rendez-vous'), ('modification_rdv', 'Modification de rendez-vous'), ('annulation_rdv', 'Annulation de rendez-vous'), ('compte_rendu_rdv', 'Compte-rendu de rendez-vous'), ('demande_beneficiaire', 'Demande du bénéficiaire'), ('information_beneficiaire', 'Information sur le bénéficiaire'), ('changement_situation', 'Changement de situation'), ('urgence_sociale', 'Urgence sociale'), ('question_aide', 'Question sur aide financière'), ('justificatif_paiement', 'Justificatif de paiement'), ('reclamation_paiement', 'Réclamation de paiement'), ('coordination_equipe', 'Coordination équipe'), ('transmission_info', "Transmission d'information"), ('demande_avis', "Demande d'avis"), ('validation_cadre', 'Validation cadre'), ('question_procedure', 'Question sur procédure'), ('demande_support', 'Demande de support'), ('signalement', 'Signalement'), ('autre', 'Autre motif')], default='autre', help_text='Motif du message', max_length=30)),
                ('beneficiaire', models.ForeignKey(blank=True, help_text='Bénéficiaire concerné par ce message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='beneficiaire.beneficiaire')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('copie', models.ForeignKey(blank=True, help_text='Cadre ou autre personne en copie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_en_copie', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('pieces_jointes', models.ManyToManyField(blank=True, help_text='Documents GED attachés au message', related_name='messages_lies', to='ged.documentged')),
                ('reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='messagerie.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('type_reception', models.CharField(choices=[('destinataire', 'Destinataire'), ('copie', 'Copie')], default='destinataire', max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts_lecture', to='messagerie.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', '-created_at'], name='messagerie__expedit_b5a365_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', '-created_at'], name='messagerie__destina_33343d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['copie', '-created_at'], name='messagerie__copie_i_34ff21_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['beneficiaire', '-created_at'], name='messagerie__benefic_5d7c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['motif'], name='messagerie__motif_421916_idx'),
        ),
        migrations.AddIndex(
            model_name='statutlecture',
            index=models.Index(fields=['utilisateur', 'lu'], name='messagerie__utilisa_f5657c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statutlecture',
            unique_together={('message', 'utilisateur')},
        ),
    ]
