# Generated by Django 6.0 on 2026-02-02 23:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaire', '0001_initial'),
        ('mds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('type_valeur', models.CharField(choices=[('STRING', 'Chaîne'), ('INTEGER', 'Entier'), ('BOOLEAN', 'Booléen'), ('JSON', 'JSON'), ('TIME', 'Heure')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='CreneauRdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('type_rdv', models.CharField(choices=[('PERMANENCE', 'Permanence'), ('IP', 'Information préoccupante'), ('ENFANCE', 'Enfance'), ('HORS_PERMANENCE', 'Hors permanence'), ('TELEPHONIQUE', 'Téléphonique'), ('VISITE_DOMICILE', 'Visite à domicile'), ('REUNION', 'Réunion'), ('FORMATION', 'Formation'), ('ADMINISTRATIF', 'Administratif')], default='PERMANENCE', max_length=20)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('VENU_RECU', 'Venu et reçu'), ('VENU_NON_RECU', 'Venu non reçu'), ('ANNULE_USAGER', 'Annulé par usager'), ('REPORT_USAGER', 'Reporté par usager'), ('ANNULE_MDS', 'Annulé par MDS'), ('REPORT_MDS', 'Reporté par MDS'), ('ABSENT', 'Absent')], default='DISPONIBLE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes_internes', models.TextField(blank=True)),
                ('priorite', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('TRES_URGENT', 'Très urgent')], default='NORMAL', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_reservation', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to=settings.AUTH_USER_MODEL)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdvs', to='beneficiaire.beneficiaire')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_crees', to=settings.AUTH_USER_MODEL)),
                ('reserve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_reserves', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='mds.mdsreception')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('RESERVATION', 'Réservation'), ('ANNULATION', 'Annulation')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='planning.creneaurdv')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='JourBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('raison', models.CharField(choices=[('FERIE', 'Jour férié'), ('FORMATION', 'Formation'), ('ABSENCE', 'Absence collective'), ('MAINTENANCE', 'Maintenance'), ('CONGE', 'Congé'), ('AUTRE', 'Autre')], max_length=20)),
                ('raison_detail', models.TextField(blank=True)),
                ('heure_debut', models.TimeField(default=datetime.time(0, 0))),
                ('heure_fin', models.TimeField(default=datetime.time(23, 59))),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mds.mdsreception')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='creneaurdv',
            index=models.Index(fields=['date', 'salle'], name='planning_cr_date_59073c_idx'),
        ),
        migrations.AddIndex(
            model_name='creneaurdv',
            index=models.Index(fields=['statut', 'date'], name='planning_cr_statut_393e72_idx'),
        ),
        migrations.AddIndex(
            model_name='creneaurdv',
            index=models.Index(fields=['agent', 'date'], name='planning_cr_agent_i_27444c_idx'),
        ),
        migrations.AddIndex(
            model_name='creneaurdv',
            index=models.Index(fields=['beneficiaire', 'date'], name='planning_cr_benefic_0e2feb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jourbloque',
            unique_together={('date', 'salle', 'agent')},
        ),
    ]
