# Generated by Django 6.0 on 2026-02-02 23:41

import django.db.models.deletion
import ged.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('identite', 'Identité'), ('administratif', 'Administratif'), ('finances', 'Finances'), ('sante', 'Santé'), ('social', 'Social'), ('contrat RSA', 'Contrat RSA'), ('logement', 'Logement'), ('divers', 'Divers')], max_length=50)),
                ('extensions_autorisees', models.JSONField(default=ged.models.get_default_extensions)),
                ('taille_max_mb', models.IntegerField(default=10)),
                ('est_sensible', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de document',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('alerte_active', models.BooleanField(default=True)),
                ('seaweedfs_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_md5', models.CharField(blank=True, db_index=True, max_length=32)),
                ('taille_octets', models.BigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('confidentialite', models.CharField(choices=[('PUBLIC', 'Public DITAS'), ('RESTREINT', 'MDS Uniquement'), ('CONFIDENTIEL', 'Nominatif (Agents autorisés)'), ('TRES_CONFIDENTIEL', 'Direction / Cadres uniquement')], default='RESTREINT', max_length=20)),
                ('statut', models.CharField(default='VALIDE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agents_autorises', models.ManyToManyField(blank=True, related_name='documents_speciaux', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_uploads', to=settings.AUTH_USER_MODEL)),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ged.documenttype')),
            ],
            options={
                'verbose_name': 'Document GED',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('seaweedfs_id', models.CharField(max_length=100, unique=True)),
                ('extension', models.CharField(max_length=10)),
                ('taille_octets', models.BigIntegerField()),
                ('hash_md5', models.CharField(db_index=True, max_length=32)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ged.documentged')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_titre_archive', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique', to='ged.documentged')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='PartageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='ged.documentged')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentged',
            index=models.Index(fields=['content_type', 'object_id'], name='ged_documen_content_0d72b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'numero')},
        ),
    ]
