# Generated by Django 6.0 on 2026-02-02 23:41

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code_mds', models.CharField(help_text='Ex: MDS01, MDS02', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('departement', models.CharField(default='Morbihan', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_fermeture', models.DateField(blank=True, null=True)),
                ('nb_agents_max', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('communes', models.JSONField(blank=True, default=list, help_text='Liste des codes INSEE')),
                ('services_proposes', models.JSONField(blank=True, default=list)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('responsable', models.ForeignKey(blank=True, help_text="L'utilisateur doit posséder la capacité de validation/encadrement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mdss_dirigees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code_mds'],
            },
        ),
        migrations.CreateModel(
            name='HoraireMDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('pause_debut', models.TimeField(blank=True, null=True)),
                ('pause_fin', models.TimeField(blank=True, null=True)),
                ('type_jour', models.CharField(choices=[('NORMAL', 'Jour normal'), ('FERIE', 'Jour férié'), ('EXCEPTION', 'Exceptionnel')], default='NORMAL', max_length=20)),
                ('mds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='mds.mds')),
            ],
            options={
                'ordering': ['mds', 'jour'],
            },
        ),
        migrations.CreateModel(
            name='DemiJourneeReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('type_demi_journee', models.CharField(choices=[('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('heure_debut', models.TimeField(default=datetime.time(9, 0), help_text="Heure de début de la demi-journée (ex: 9h pour le matin, 13h30 pour l'après-midi)", verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(default=datetime.time(12, 0), help_text="Heure de fin de la demi-journée (ex: 12h pour le matin, 17h pour l'après-midi)", verbose_name='Heure de fin')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demi_journees_reception', to=settings.AUTH_USER_MODEL)),
                ('mds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demi_journees_reception', to='mds.mds')),
            ],
            options={
                'verbose_name': 'Demi-journée de réception',
                'verbose_name_plural': 'Demi-journées de réception',
            },
        ),
        migrations.CreateModel(
            name='MDSReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=100)),
                ('type_salle', models.CharField(default='BUREAU', max_length=20)),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('actif', models.BooleanField(default=True)),
                ('horaire_debut', models.TimeField(default='09:00')),
                ('horaire_fin', models.TimeField(default='17:00')),
                ('disponible_lundi', models.BooleanField(default=True, help_text='Cocher si la salle est ouverte le lundi', verbose_name='Disponible le lundi')),
                ('disponible_mardi', models.BooleanField(default=True, verbose_name='Disponible le mardi')),
                ('disponible_mercredi', models.BooleanField(default=True, verbose_name='Disponible le mercredi')),
                ('disponible_jeudi', models.BooleanField(default=True, verbose_name='Disponible le jeudi')),
                ('disponible_vendredi', models.BooleanField(default=True, verbose_name='Disponible le vendredi')),
                ('disponible_samedi', models.BooleanField(default=False, verbose_name='Disponible le samedi')),
                ('disponible_dimanche', models.BooleanField(default=False, verbose_name='Disponible le dimanche')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles_reception', to='mds.mds')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserMDSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('principale', models.BooleanField(default=False, help_text='MDS de rattachement par défaut')),
                ('peut_gerer_utilisateurs', models.BooleanField(default=False, help_text="Droit d'administration locale (Cadre)")),
                ('peut_voir_statistiques', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('role_specifique', models.CharField(blank=True, help_text='Ex: Référent RSA', max_length=100)),
                ('bureau', models.CharField(blank=True, max_length=50)),
                ('telephone_interne', models.CharField(blank=True, max_length=20)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_utilisateurs', to='mds.mds')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils_mds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mds',
            index=models.Index(fields=['code_mds'], name='mds_mds_code_md_ffde58_idx'),
        ),
        migrations.AddIndex(
            model_name='mds',
            index=models.Index(fields=['ville', 'active'], name='mds_mds_ville_0fc8fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horairemds',
            unique_together={('mds', 'jour')},
        ),
        migrations.AlterUniqueTogether(
            name='demijourneereception',
            unique_together={('agent', 'mds', 'jour_semaine', 'type_demi_journee')},
        ),
        migrations.AddIndex(
            model_name='usermdsprofile',
            index=models.Index(fields=['user', 'actif'], name='mds_usermds_user_id_d14bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='usermdsprofile',
            index=models.Index(fields=['mds', 'actif'], name='mds_usermds_mds_id_782c2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermdsprofile',
            unique_together={('user', 'mds')},
        ),
    ]
