# Generated by Django 6.0 on 2026-02-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demijourneereception',
            name='heure_debut',
            field=models.TimeField(help_text="Heure de début de la demi-journée (ex: 9h pour le matin, 13h30 pour l'après-midi)", verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='demijourneereception',
            name='heure_fin',
            field=models.TimeField(help_text="Heure de fin de la demi-journée (ex: 12h pour le matin, 17h pour l'après-midi)", verbose_name='Heure de fin'),
        ),
    ]
