# Generated by Django 6.0 on 2026-05-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mds", "0002_alter_demijourneereception_heure_debut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mdsreception",
            name="est_externe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mdsreception",
            name="mds_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="MDS qui a créé cette salle externe (filtrage territorial)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mds.mds",
            ),
        ),
    ]
