# Generated by Django 6.0 on 2026-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mds', '0003_mdsreception_est_externe_mdsreception_mds_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='demijourneereception',
            name='lieu_externe',
            field=models.CharField(blank=True, help_text='Nom du lieu si externe (CCAS, école, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='demijourneereception',
            name='type_lieu',
            field=models.CharField(choices=[('MDS', 'En MDS'), ('EXTERNE', 'Lieu externe')], default='MDS', max_length=10),
        ),
    ]
